### ISSUE TITLE
`lookup()`'s behavior is different from `minizinc --solver <s>`

### ISSUE THREAD

**Issue by LebedevRI** [MiniZinc/minizinc-python#170]
Concretely, i've wanted to run minizinc tests with the solvers
that actually got built into `minizinc`, not the `executable`s.
And that is surprisingly painful to do, apparently.

My first idea was to use a config, and just use `tagDefaults`
to redirect e.g. `chuffed` to e.g. `chuffed_internal`, that didn't work.
I now realize that it really only allows tag redirects, nothing more.

The second approach was to move away default solver configs,
and add my own stub config much like how `chuffed_internal.msc`
is produced. This works for `chuffed_internal`, but not for `gecode`,
because for latter, the tag has to be `org.minizinc.gecode_presolver`,
and the function does not deal with substring matches:
https://github.com/MiniZinc/minizinc-python/blob/7b41dc50c8ea6fd5c93e0fdc3e1c29c5567ff091/src/minizinc/solver.py#L111-L132

I suppose i can workaround that by adding `gecode` into `"tags"`.
But my problem really is that this config for `org.minizinc.gecode_presolver` works with `minizinc` proper...

(Also, test infra has an issues with dealing with missing solver configs,
even for solvers that aren't enabled through the command line.)

**Comment by LebedevRI** [comment]
> I suppose i can workaround that by adding `gecode` into `"tags"`.

Lovely, that works, and now i get ~~80~~ 70 (after `s/-Ggecode/-Ggecode_presolver/`) failed tests, all but one coming from gecode. So fascinating :]

**Comment by Dekker1** [comment]
I've read this issue a few times, but I'm still not clear on what the difference is that you're seeing.

Neither in MiniZinc command line interface, nor in the MiniZinc Python interface, does asking for `gecode` match `org.minizinc.gecode_presolver` identifier (and similarly `chuffed` does not match the `chuffed_internal` solver). This is intended as these are separate that can have different behaviour. 

Adding a tag that matches both possible solvers, would be the intended approach if you want to match any of a given set of solvers.

**Comment by LebedevRI** [comment]
I think the issue is quite self-explanatory: `lookup` does not quite do what it claims to do.
>          configuation matching the given tag. Tags are matched in similar to 
>         ``minizinc --solver tag``. The order of solver configuration attributes 
>         that are considered is: full id, id ending, tags. 

IOW, using the exact same pattern leads to different results as compared to when using the `--solver` option.

**Comment by Dekker1** [comment]
So what solver configurations are present, what lookup query did you provide, and what was the result for the different systems?

**Comment by LebedevRI** [comment]
The easiest way to see that is to build minizinc with gecode (and no other solver),
ensure that the `gecode_internal.msc` (`gecode_presolver.msc`?) solver config is present and found,
then to ensure that no other solver config is present and found,
and finally try running minizinc tests and see that they are all failing,
even though you've clearly have a gecode solver avaliable.

**Comment by Dekker1** [comment]
But when you build MiniZinc with Gecode and run `minizinc --solver gecode` it will also not find a solver. You have to explicitly use `minizinc --solver gecode_presolver` to be able to use this solver.

I'm not sure if you mean that you add another `gecode_internal.msc` file to point at the Gecode presolver, but then I would have to see this file to be able to consider it.

So, as far as I'm aware, the behaviour is the same.

**Comment by LebedevRI** [comment]
Unfortunately two months later i do not remember much asides from what i've documented in the issue.
Let's pretend i hallucinated it, but it really does seem like there is no way to test built-in solvers.
