### ISSUE TITLE
optimisation_level=0 has no effect

### ISSUE THREAD

**Issue by jmjrawlings-azn** [MiniZinc/minizinc-python#23]
As per title - passing `optimisation_level=0` does not result in `-O 0` being passed to the CLI.

Inside of CLI/instance.py  under `CLIInstance.solutions`  I believe that

```python
# Set compiler optimisation level if specified
if optimisation_level:
    cmd.extend(["-O", str(optimisation_level)])
```

should be 

```python
# Set compiler optimisation level if specified
if optimisation_level is not None:
    cmd.extend(["-O", str(optimisation_level)])
```

thanks for the great package!

**Comment by Dekker1** [comment]
Hi @J-M-J-R,

Thank you for reporting the issue and providing the fix. It seems I should be more careful in non statically typed languages.

I'll merge the fix into develop in a minute
