### ISSUE TITLE
Minizinc console opens at every instance

### ISSUE THREAD

**Issue by guillaumeproulx98** [MiniZinc/minizinc-python#27]
An empty minizinc.EXE console opens everytime an instance is started. It also becomes the active window and perturbs tje user. Could there be a parameter to be able to not make it appear?

**Comment by Dekker1** [comment]
I haven't really seen this behaviour (and haven't heard about this from other users using MiniZinc Python on Windows). Is this something that always happens on windows machines @cyderize ?

**Comment by cyderize** [comment]
I haven't been able to reproduce this on my Windows 10 machine on `stable`/`develop`.

@guillaumeproulx98 What versions of Windows, Python, minizinc-python and minizinc are you using? I might be able to reproduce it with some more information.

**Comment by guillaumeproulx98** [comment]
I run on :
Windows 19042.867
Python 3.7.3
Minizinc Python 0.4.2
I think my Minizinc is 2.5.3 (Minizinc to Flatzinc version)
I run Python on Spyder 3.3.6

**Comment by Dekker1** [comment]
We had a look, but were unable to recreate your issue.

Could you see if using the development version of MiniZinc Python changes anything? 
```
pip install git+https://github.com/MiniZinc/minizinc-python.git
```

Jason contributed some changes recently that were supposed to help with the interrupting of MiniZinc Python on Windows. They make the fact that Windows should hide any window it creates explicit and might solve your problem as well.
