### ISSUE TITLE
list of installed solvers?

### ISSUE THREAD

**Issue by tias** [MiniZinc/minizinc-python#32]
Hi,

Could you add to Solver a function to get the list of _installed_ solvers?

I see the logic of getting the list of solves is in lookup(), but it is not exported. Furthermore, it contains entries not supported by the library (e.g. findMUS, according to a separate entry), which would ideally be filtered out?

Finally, it would be even better if that list could get further filtered to only the systems installed locally, e.g. that minizinc can run. I don't have cplex on this machine so ideally it would not be shown (perhaps detectable with the version being empty, or the executable?

Thanks in advance,
Tias

(I could also create a pull request, if you recommend what way is best to check whether a solver is supported on the local machine, and what to filter out from globalizer/findmus/api/...)

**Comment by Dekker1** [comment]
Hi Tias,

I will have a look at this. As you said finding the solvers themselves is not the hard part, but the filtering might be very ambiguous. FindMUS is supported, but there is no integrated way to parse its results. So it depends on your definition of "useful".
