### ISSUE TITLE
'flatTime' statistic returned as float instead of timedelta under MiniZinc >= 2.6.0

### ISSUE THREAD

**Issue by jmjrawlings** [MiniZinc/minizinc-python#55]
As per title:

The issue seems to be that newer minizinc versions have their solutions parsed through `_parse_stream_obj` which does not call any of the logic contained in `set_stat`

I was able to get the expected behaviour by changing `minizinc/CLI/instance.py` line 547 

from
```python
elif obj["type"] == "statistics":
    statistics.update(obj["statistics"])
```
to

```python
elif obj["type"] == "statistics":
    for key,val in obj['statistics'].items():
        set_stat(statistics, key, str(val))
```

**Comment by Dekker1** [comment]
Thank you for reporting the issue. This was indeed an oversight on my part. The fix has been committed in 1e35852
