### ISSUE TITLE
ImportError: cannot import name 'Instance' from 'minizinc' 

### ISSUE THREAD

**Issue by deluxerootit** [MiniZinc/minizinc-python#56]
I have Ubuntu20 as OS and my python version is python3. When I try to import Instance from z3 using: import Instance from z3 , I get the following error :

ImportError: cannot import name 'Instance' from 'minizinc' (/home/maryam/.local/lib/python3.8/site-packages/minizinc/init.py)

Any idea?

**Comment by Dekker1** [comment]
As I mentioned in the other issue. Did you make sure that you do not have an Python model (including the current script) that is named `minizinc`? (i.e., `minizinc.py` or `minizinc/__init__.py`)

**Comment by deluxerootit** [comment]
I have /home/maryam/.local/lib/python3.8/site-packages/minizinc/__init__.py  but I do not know why it is in my system. I think Minizinc installation added it. 

Now that I want  to import Instance from z3, I followed Minizinc installation from https://www.minizinc.org/doc-2.6.2/en/installation.html section 1.2.2.3. Archive. I did:
tar xf MiniZincIDE-2.6.2-bundle-linux-x86_64.tgz
export PATH=MiniZincIDE-2.6.2-bundle-linux-x86_64/bin:$PATH
export LD_LIBRARY_PATH=MiniZincIDE-2.6.2-bundle-linux-x86_64/lib:$LD_LIBRARY_PATH
export QT_PLUGIN_PATH=MiniZincIDE-2.6.2-bundle-linux-x86_64/plugins:$QT_PLUGIN_PATH

when I run: ~/Downloads/MiniZincIDE-2.6.2-bundle-linux-x86_64/bin/minizinc --solver Chuffed --solver-statistics -O1 --time-limit 200 model.mzn 8x8.dzn  it works. 

But when I make a .py file and import Instance from z3 inside it and execute it, I get the following error:

/home/maryam/.local/lib/python3.8/site-packages/minizinc/__init__.py:26: RuntimeWarning: MiniZinc was not found on the system. No default driver could be initialised.
  warnings.warn(
Traceback (most recent call last):
  File "z3_import.py", line 1, in <module>
    from minizinc import Model, Solver, Instance
ImportError: cannot import name 'Instance' from 'minizinc' (/home/maryam/.local/lib/python3.8/site-packages/minizinc/__init__.py)


Then I run: sudo apt-get install minizinc and re execute my .py file I get:
/home/maryam/.local/lib/python3.8/site-packages/minizinc/__init__.py:32: RuntimeWarning: The MiniZinc version found on the system is incompatible with MiniZinc Python:
The MiniZinc driver found at '/usr/bin/minizinc' has version (2, 4, 2). The minimal required version is (2, 5, 0).
 No default driver could be initialised.
  warnings.warn(
Traceback (most recent call last):
  File "z3_import.py", line 1, in <module>
    from minizinc import Model, Solver, Instance
ImportError: cannot import name 'Instance' from 'minizinc' (/home/maryam/.local/lib/python3.8/site-packages/minizinc/__init__.py)

Output of echo $PATH is:
echo $PATH
MiniZincIDE-2.6.2-bundle-linux-x86_64/bin:/opt/ros/noetic/bin:/home/maryam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Any idea?

**Comment by Dekker1** [comment]
The `Instance` class only becomes available once a correct `Driver` can be initialised. In this case the library actually warns that this isn't the case:
```/home/maryam/.local/lib/python3.8/site-packages/minizinc/init.py:32: RuntimeWarning: The MiniZinc version found on the system is incompatible with MiniZinc Python:
The MiniZinc driver found at '/usr/bin/minizinc' has version (2, 4, 2). The minimal required version is (2, 5, 0).
No default driver could be initialised.
```

MiniZinc Python will look for MiniZinc on the `PATH` variable unless instructed otherwise. In this case it finds only an incompatible version. I would suggest you analyse the Python scripts that you use to ensure that some other part is not erasing this executable path beforehand.
