### ISSUE TITLE
Asyncronous environment calling, Anaconda.

### ISSUE THREAD

**Issue by SJMC29** [MiniZinc/minizinc-python#73]
![image](https://user-images.githubusercontent.com/70499799/220460772-56b15da1-50de-4014-81dd-7bd4f602deb6.png)

We're using an Anaconda virtual environment and the Path is already configured but we are still getting this error. If we try to run it using solve_async(), it shows this:

![image](https://user-images.githubusercontent.com/70499799/220461319-d5fd6762-e35f-48a4-8c68-8a8e9ebd2b05.png)

This example is from the documentation: https://minizinc-python.readthedocs.io/en/latest/getting_started.html

**Comment by Dekker1** [comment]
When you call an `async` function in python, you have to use `await` to get the result. As such, the correct usage would be:

```
result = await instance.solve_async()
````

See Python's documentation for more information: https://docs.python.org/3/library/asyncio.html

**Comment by borisalmonacid** [comment]
When changing await and sync, it gives me the error message that is in the PDF file:
[minizinc-python.pdf](https://github.com/MiniZinc/minizinc-python/files/13628098/minizinc-python.pdf)

**Comment by Dekker1** [comment]
I think this was fixed in https://github.com/MiniZinc/minizinc-python/pull/91
