### ISSUE TITLE
Need information for output (json)

### ISSUE THREAD

**Issue by borisalmonacid** [MiniZinc/minizinc-python#77]
Hello,
Is there a **`function or a command or a flag`** to be able to have the solutions (results) directly to `json or dict`? Without having to indicate directly in the code which variables should be printed.

I have seen that the `instance.output()` function generates a dictionary with the model variables and the dictionary can be obtained. But I wanted to see if there was a direct way.

```
import minizinc
from minizinc import Result, Solver, Instance

model = minizinc.Model()
model.add_string("""
int: n=4;
array [1..n] of var 1..n: q;
include "alldifferent.mzn";
constraint alldifferent(q);
constraint alldifferent(i in 1..n)(q[i] + i);
constraint alldifferent(i in 1..n)(q[i] - i);
""")

solver = Solver.lookup("gecode")

instance = Instance(solver, model)

result: Result = instance.solve()
print(result["q"])                        # <------ no this way
print(result)                             # "Solution(q=[3, 1, 4, 2], _checker='')"    <--- this is a string.
print(instance.output())                  # {'q': typing.List[int], '_checker': <class 'str'>}
```

**Comment by Dekker1** [comment]
The `Result` object is a wrapper that contains the `Status`, `statistics`, and a `solution` (https://minizinc-python.readthedocs.io/en/latest/api.html#minizinc.result.Result.solution) object. The last one is an object only containing the model instance solution. So I think `result.solution` will likely be what you would like to do.

Note, however, that the type of solution is by default a `dataclass` generated for the model. So if you really want a dictionary, you will have to change the output type, as shown in the example in the documentation: https://minizinc-python.readthedocs.io/en/latest/advanced_usage.html#custom-output-type

I'm pretty sure that you can do `model.output_type = dict` to get a dictionary, but I'm not 100% sure.

**Comment by borisalmonacid** [comment]
thanks, understand, thanks 

this code works

```
d: dict() = {}
for key in instance.output:
    if key != '_checker':
        d[key] = result[(key)]
        
print(d)                 # {'q': [3, 1, 4, 2]}
```

**Comment by Dekker1** [comment]
That was not what I meant. The MiniZinc Python infrastructure can also be set to store solutions in dictionaries as follows:

```
import minizinc
from minizinc import Result, Solver, Instance

model = minizinc.Model()
model.add_string(
    """
int: n=4;
array [1..n] of var 1..n: q;
include "alldifferent.mzn";
constraint alldifferent(q);
constraint alldifferent(i in 1..n)(q[i] + i);
constraint alldifferent(i in 1..n)(q[i] - i);
"""
)
model.output_type = dict

solver = Solver.lookup("gecode")

instance = Instance(solver, model)

result: Result = instance.solve()
d = result.solution
print(d)
```

**Comment by borisalmonacid** [comment]
thanks, this works !!
